version: '3.8'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./celeryprj
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./celeryprj:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build:
      context: ./celeryprj
    command: celery --app=celeryprj worker -l INFO 
    volumes:
      - ./celeryprj:/usr/src/app/
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django

  celery2:
    container_name: celery2
    build:
      context: ./celeryworker
      dockerfile: Dockerfile
    command: celery -A celerytask worker --loglevel=INFO 
    volumes:
      - ./celeryworker:/usr/src/app/
    depends_on:
      - redis
      - django
    