version: '3.8'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./celeryprj
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./celeryprj:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build:
      context: ./celeryprj
    command: celery -A celeryprj worker -l info
    volumes:
      - ./celeryprj:/usr/src/app/
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - redis
      - django
    

    